In [9]:
from api_token import token
import todoist as td
import pandas as pd
# import time
import datetime

In [70]:
api = td.TodoistAPI(token)

# get the latest data from api
api.sync();

In [71]:
# this will convert from a individual todoist projects to dictionary
projects = [project.data for project in api.state['projects']]

In [72]:
# use dictionary to create data frame
df_projects = pd.DataFrame(projects)

# view data frame
df_projects.head(20)

,child_order,collapsed,color,has_more_notes,id,inbox_project,is_archived,is_deleted,is_favorite,name,parent_id,shared,sync_id
0,0,0,48,False,2240336392,True,0,0,0,Inbox,None,False,None
1,1,0,31,False,2240338076,NaN,0,0,0,‚ù∂ This Week,None,False,None
2,2,0,46,False,2250738735,NaN,0,0,0,‚ù∑ Next Week,None,False,None
3,3,0,33,False,2250738747,NaN,0,0,0,‚ù∏ This Month,None,False,None
4,4,0,34,False,2250738761,NaN,0,0,0,‚ùπ Next Month,None,False,None
5,5,0,47,False,2250741928,NaN,0,0,0,‚ù∫ Further Than Next Month,None,False,None
6,6,0,47,False,2250742579,NaN,0,0,0,üß† Project Ideas,None,False,None
7,7,0,31,False,2240553789,NaN,0,0,0,üöß Backlog üöß,None,False,None
8,8,0,30,False,2240717407,NaN,0,0,0,‚è± Routines,None,False,None
9,9,0,32,False,2240338162,NaN,0,0,0,ü•ì JET,None,False,None
10,10,0,38,False,2240484947,NaN,0,0,0,üè° Reign Property,None,False,None

In [19]:
# Create tasks database
tasks = [task.data for task in api.state['items']]

In [24]:
df_tasks = pd.DataFrame(tasks)
df_tasks[df_tasks['checked'] ==1].head(10)

,added_by_uid,assigned_by_uid,checked,child_order,collapsed,content,date_added,date_completed,day_order,due,...,in_history,is_deleted,labels,parent_id,priority,project_id,responsible_uid,section_id,sync_id,user_id
152,28966387,None,1,3,0,**05** Add to interview prep pack,2020-09-26T06:35:16Z,2020-12-30T21:11:12Z,-1,"{'date': '2020-12-30', 'is_recurring': False, ...",...,1,0,[2155605676],NaN,1,2240338076,None,30384015.0,None,28966387
165,28966387,None,1,1,0,Change tv license for mum,2020-11-08T13:10:05Z,2021-01-01T13:25:44Z,-1,None,...,1,0,[],4.332599e+09,1,2240338076,None,30384015.0,None,28966387
170,28966387,None,1,1,0,**04** Set up a [new tv licence](https://www.t...,2020-11-13T10:37:08Z,2021-01-01T13:25:44Z,-1,"{'date': '2021-01-01', 'is_recurring': False, ...",...,1,0,[2155605676],NaN,4,2240338076,None,30384015.0,None,28966387
194,28966387,None,1,1,0,**08** 2021 Vision Board + Aspirational Goals,2020-11-21T17:00:50Z,2020-12-28T20:44:31Z,-1,"{'date': '2020-12-28', 'is_recurring': False, ...",...,1,0,[2155605676],NaN,1,2240338076,None,30384001.0,None,28966387
196,28966387,None,1,4,0,Call Mum,2020-11-21T17:05:07Z,2021-01-01T12:38:11Z,-1,"{'date': '2021-01-01', 'is_recurring': False, ...",...,1,0,[],NaN,1,2240717407,None,30060955.0,None,28966387
225,28966387,None,1,5,0,**05b** File nails,2020-12-03T06:05:28Z,2021-01-01T23:04:26Z,-1,"{'date': '2021-01-02', 'is_recurring': False, ...",...,1,0,[],NaN,1,2240717407,None,NaN,None,28966387
231,28966387,None,1,4,0,**05** Add to interview prep doc,2020-12-09T20:40:39Z,2020-12-30T21:05:24Z,-1,"{'date': '2020-12-30', 'is_recurring': False, ...",...,1,0,[],NaN,1,2240338076,None,30384015.0,None,28966387
251,28966387,None,1,5,0,**07** 2021 Finance + Savings Goals,2020-12-20T21:33:11Z,2020-12-28T19:10:23Z,-1,"{'date': '2020-12-28', 'is_recurring': False, ...",...,1,0,[],NaN,1,2240338076,None,30384001.0,None,28966387
265,28966387,None,1,6,0,Order protein powder,2020-12-24T10:59:18Z,2020-12-29T10:07:54Z,-1,"{'date': '2021-01-07', 'is_recurring': False, ...",...,1,0,[],NaN,1,2250738735,None,NaN,None,28966387
266,28966387,None,1,5,0,Call dad,2020-12-26T20:54:56Z,2021-01-01T12:38:10Z,-1,"{'date': '2021-01-01', 'is_recurring': False, ...",...,1,0,[],NaN,1,2240717407,None,30060955.0,None,28966387

In [66]:
today = datetime.date.today()
yesterday = today - datetime.timedelta(days = 1)
tomorrow = today + datetime.timedelta(days = 1) 
print('Yesterday : ',yesterday)
print('Today : ',today)
print('Tomorrow : ',tomorrow)
yday_start = str(yesterday)+"T00:00:00Z"
yday_end = str(yesterday)+"T23:59:59Z"
print(yday_start)
print(yday_end)

Yesterday :  2021-01-01
Today :  2021-01-02
Tomorrow :  2021-01-03
2021-01-01T00:00:00Z
2021-01-01T23:59:59Z

In [69]:
# Get list of tasks completed in the last day
print(len(api.completed.get_all(since = yday_start, until = yday_end)['items']))
for item in api.completed.get_all(since = yday_start, until = yday_end)['items']:
    print (item)
# print(api.completed.get_all(since = yday))
# for d in api.completed.get_all(since ='2020-12-29T00:00')["projects"]:
#     print(d)

11
{'completed_date': '2021-01-01T23:17:35Z', 'content': '**02** [100 days of code](https://www.udemy.com/course/100-days-of-code/learn/)', 'id': 4169634811, 'meta_data': None, 'project_id': 2240338076, 'task_id': 4411952967, 'user_id': 28966387}
{'completed_date': '2021-01-01T23:04:29Z', 'content': '**05b** File nails', 'id': 4169621549, 'meta_data': None, 'project_id': 2240717407, 'task_id': 4384309791, 'user_id': 28966387}
{'completed_date': '2021-01-01T21:25:00Z', 'content': "**01** Make notes on Data Engineer JD's", 'id': 4169505119, 'meta_data': None, 'project_id': 2240338076, 'task_id': 4435958173, 'user_id': 28966387}
{'completed_date': '2021-01-01T19:59:50Z', 'content': '**00** Weekly food shop üåΩ & other bits', 'id': 4169398991, 'meta_data': None, 'project_id': 2240717407, 'task_id': 4135956061, 'user_id': 28966387}
{'completed_date': '2021-01-01T18:07:16Z', 'content': '**00** Plan my day', 'id': 4169254218, 'meta_data': None, 'project_id': 2240338076, 'task_id': 4355453459, 'user_id': 28966387}
{'completed_date': '2021-01-01T13:25:48Z', 'content': '**04** Set up a [new tv licence](https://www.tvlicensing.co.uk/cs/pay-for-your-tv-licence/index.app) for mum @personal', 'id': 4168897147, 'meta_data': None, 'project_id': 2240338076, 'task_id': 4332598593, 'user_id': 28966387}
{'completed_date': '2021-01-01T13:25:48Z', 'content': 'Change tv license for mum', 'id': 4168897146, 'meta_data': None, 'project_id': 2240338076, 'task_id': 4318653721, 'user_id': 28966387}
{'completed_date': '2021-01-01T13:10:44Z', 'content': 'Fix 12 week year spreadsheet', 'id': 4168882399, 'meta_data': None, 'project_id': 2240338076, 'task_id': 4452051922, 'user_id': 28966387}
{'completed_date': '2021-01-01T12:38:16Z', 'content': 'Call Mum', 'id': 4168851328, 'meta_data': None, 'project_id': 2240717407, 'task_id': 4354160771, 'user_id': 28966387}
{'completed_date': '2021-01-01T12:38:16Z', 'content': 'Call dad', 'id': 4168851326, 'meta_data': None, 'project_id': 2240717407, 'task_id': 4441236855, 'user_id': 28966387}
{'completed_date': '2021-01-01T12:38:00Z', 'content': '**01a:** Laundry and bathroom items üëñ', 'id': 4168851111, 'meta_data': None, 'project_id': 2240717407, 'task_id': 4061245089, 'user_id': 28966387}

In [ ]:
# Create tasks activities